In [15]:
import numpy as np

In [17]:
#Numpy array
[1,3,5,'A',6]

[1, 3, 5, 'A', 6]

In [19]:
x = np.array([45,67,57,60])
print(x)
print(type(x))
print(x.dtype)

[45 67 57 60]
<class 'numpy.ndarray'>
int32


In [27]:
a1 = np.array([45. 67. 57. 9.8])
print(a1)
print(type(a1))
print(a1.dtype)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1806012176.py, line 1)

In [25]:
a2 = np.array([[20,40],[30,60]])
print(a2)
print(type(a2))
print(a2.dtype)
print(a2.shape)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
int32
(2, 2)


In [35]:
a = np.array([10,20,30,40])
b = a.reshape(4,1)
print(b)
print(b.shape)

[[10]
 [20]
 [30]
 [40]]
(4, 1)


In [41]:
# Create an array with arange 
c = np.arange(3,10)
print(c)
type(c)

[3 4 5 6 7 8 9]


numpy.ndarray

In [43]:
d = np.array([1.3467, 3.10987, 4.91236])
print(d)
np.around(d,2)

[1.3467  3.10987 4.91236]


array([1.35, 3.11, 4.91])

In [45]:
d = np.array([1.3467, 3.10987, 4.912])
print(d)
print(np.around(np.sqrt(d),2))

[1.3467  3.10987 4.912  ]
[1.16 1.76 2.22]


In [47]:
a1 = np.array([[3,4,5,8],[7,2,8,np.NAN]])
print(a1)
print(a1.shape)
print(a1.dtype)

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]
(2, 4)
float64


a1.reshape(4,2)
a1.dtype

In [50]:
print(a1.shape)
print(a1.dtype)

(2, 4)
float64


In [52]:
# use od astype() to convert the data type
a1 = np.array([[3,4,5,8],[7,2,8,np.NAN]])
print(a1)
a1.dtype

[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [54]:
# Mathematical operations in rows and cols
a2 = np.array([[3,4,6,],[7,90,10],[4,6,12]])
a2

array([[ 3,  4,  6],
       [ 7, 90, 10],
       [ 4,  6, 12]])

In [58]:
a2 = np.array([[3,4,6,],[7,90,10],[4,6,12]])
a2
a2.sum(axis=0)

array([ 14, 100,  28])

In [60]:
a2 = np.array([[3,4,6,],[7,90,10],[4,6,12]])
a2
a2.sum(axis=1)

array([ 13, 107,  22])

In [64]:
print(a2.sum(axis = 1))
print(a2.sum(axis = 0))

[ 13 107  22]
[ 14 100  28]


In [68]:
print(a2)
print(a2.mean(axis = 0))
print(a2.mean(axis = 1))

[[ 3  4  6]
 [ 7 90 10]
 [ 4  6 12]]
[ 4.66666667 33.33333333  9.33333333]
[ 4.33333333 35.66666667  7.33333333]


In [70]:
print(a2)
print(a2.mean(axis = 0))
print(a2.mean(axis = 1))

[[ 3  4  6]
 [ 7 90 10]
 [ 4  6 12]]
[ 4.66666667 33.33333333  9.33333333]
[ 4.33333333 35.66666667  7.33333333]


In [74]:
a3 = np.array([[3,4,6,],[7,90,10],[4,6,12]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[ 3  4  6]
 [ 7 90 10]
 [ 4  6 12]]
[[ 0  4  6]
 [ 7  0 10]
 [ 4  6  0]]


In [82]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = np.matmul(A,B)
print(C)
print(A.T)
print(B.T)


[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [84]:
print(A.T)
print(B.T)


[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


a4 = np.array([[1,2,3],[4,5,6],[3,2,1],[6,5,4]])
print(a4)